[project]
name = "null-project-name-exploration"
version = "0.1.0"
requires-python = ">=3.9"
dependencies = [
    "aind-data-access-api",
    "pandas",
]

[build-system]
requires = ["setuptools"]
build-backend = "setuptools.build_meta"

[tool.setuptools]
py-modules = []
